package timezone

import (
	"fmt"
	"time"
)

var countryTimezone = map[string]string{
	"AD": "Europe/Andorra",
	"AE": "Asia/Dubai",
	"AF": "Asia/Kabul",
	"AG": "America/Antigua",
	"AI": "America/Anguilla",
	"AL": "Europe/Tirane",
	"AM": "Asia/Yerevan",
	"AO": "Africa/Luanda",
	"AR": "America/Argentina/Buenos_Aires",
	"AT": "Europe/Vienna",
	"AU": "Australia/Canberra", // approximated as Australia/Sydney
	"AW": "America/Aruba",
	"AZ": "Asia/Baku",
	"BA": "Europe/Sarajevo",
	"BB": "America/Barbados",
	"BD": "Asia/Dhaka",
	"BE": "Europe/Brussels",
	"BF": "Africa/Ouagadougou",
	"BG": "Europe/Sofia",
	"BH": "Asia/Bahrain",
	"BI": "Africa/Bujumbura",
	"BJ": "Africa/Porto-Novo",
	"BN": "Asia/Brunei",
	"BO": "America/La_Paz",
	"BR": "America/Brasilia",
	"BS": "America/Nassau",
	"BT": "Asia/Thimphu",
	"BW": "Africa/Gaborone",
	"BY": "Europe/Minsk",
	"BZ": "America/Belize",
	"CA": "America/Ottawa", // approximated as America/Toronto
	"CD": "Africa/Kinshasa",
	"CF": "Africa/Bangui",
	"CG": "Africa/Brazzaville",
	"CH": "Europe/Zurich",
	"CI": "Africa/Abidjan",
	"CL": "America/Santiago",
	"CM": "Africa/Douala",
	"CN": "Asia/Beijing",
	"CO": "America/Bogota",
	"CR": "America/Costa_Rica",
	"CU": "America/Havana",
	"CV": "Atlantic/Cape_Verde",
	"CY": "Asia/Nicosia",
	"CZ": "Europe/Prague",
	"DE": "Europe/Berlin",
	"DJ": "Africa/Djibouti",
	"DK": "Europe/Copenhagen",
	"DM": "America/Dominica",
	"DO": "America/Santo_Domingo",
	"DZ": "Africa/Algiers",
	"EC": "America/Guayaquil",
	"EE": "Europe/Tallinn",
	"EG": "Africa/Cairo",
	"ER": "Africa/Asmara",
	"ES": "Europe/Madrid",
	"ET": "Africa/Addis_Ababa",
	"FI": "Europe/Helsinki",
	"FJ": "Pacific/Fiji",
	"FM": "Pacific/Pohnpei",
	"FR": "Europe/Paris",
	"GA": "Africa/Libreville",
	"GB": "Europe/London",
	"GD": "America/Grenada",
	"GE": "Asia/Tbilisi",
	"GH": "Africa/Accra",
	"GM": "Africa/Banjul",
	"GN": "Africa/Conakry",
	"GQ": "Africa/Malabo",
	"GR": "Europe/Athens",
	"GT": "America/Guatemala",
	"GW": "Africa/Bissau",
	"GY": "America/Guyana",
	"HK": "Asia/Hong_Kong",
	"HN": "America/Tegucigalpa",
	"HR": "Europe/Zagreb",
	"HT": "America/Port-au-Prince",
	"HU": "Europe/Budapest",
	"ID": "Asia/Jakarta",
	"IE": "Europe/Dublin",
	"IL": "Asia/Jerusalem",
	"IN": "Asia/Kolkata",
	"IQ": "Asia/Baghdad",
	"IR": "Asia/Tehran",
	"IS": "Atlantic/Reykjavik",
	"IT": "Europe/Rome",
	"JM": "America/Jamaica",
	"JO": "Asia/Amman",
	"JP": "Asia/Tokyo",
	"KE": "Africa/Nairobi",
	"KG": "Asia/Bishkek",
	"KH": "Asia/Phnom_Penh",
	"KI": "Pacific/Tarawa",
	"KM": "Indian/Comoro",
	"KN": "America/St_Kitts",
	"KP": "Asia/Pyongyang",
	"KR": "Asia/Seoul",
	"KW": "Asia/Kuwait",
	"KY": "America/Cayman",
	"KZ": "Asia/Astana",
	"LA": "Asia/Vientiane",
	"LB": "Asia/Beirut",
	"LC": "America/St_Lucia",
	"LI": "Europe/Vaduz",
	"LK": "Asia/Colombo",
	"LR": "Africa/Monrovia",
	"LS": "Africa/Maseru",
	"LT": "Europe/Vilnius",
	"LU": "Europe/Luxembourg",
	"LV": "Europe/Riga",
	"LY": "Africa/Tripoli",
	"MA": "Africa/Rabat",
	"MC": "Europe/Monaco",
	"MD": "Europe/Chisinau",
	"ME": "Europe/Podgorica",
	"MG": "Indian/Antananarivo",
	"MH": "Pacific/Majuro",
	"MK": "Europe/Skopje",
	"ML": "Africa/Bamako",
	"MM": "Asia/Yangon",
	"MN": "Asia/Ulaanbaatar",
	"MO": "Asia/Macau",
	"MR": "Africa/Nouakchott",
	"MT": "Europe/Malta",
	"MU": "Indian/Mauritius",
	"MV": "Indian/Maldives",
	"MW": "Africa/Lilongwe",
	"MX": "America/Mexico_City",
	"MY": "Asia/Kuala_Lumpur",
	"MZ": "Africa/Maputo",
	"NA": "Africa/Windhoek",
	"NE": "Africa/Niamey",
	"NG": "Africa/Abuja",
	"NI": "America/Managua",
	"NL": "Europe/Amsterdam",
	"NO": "Europe/Oslo",
	"NP": "Asia/Kathmandu",
	"NR": "Pacific/Nauru",
	"NZ": "Pacific/Auckland",
	"OM": "Asia/Muscat",
	"PA": "America/Panama",
	"PE": "America/Lima",
	"PG": "Pacific/Port_Moresby",
	"PH": "Asia/Manila",
	"PK": "Asia/Karachi",
	"PL": "Europe/Warsaw",
	"PT": "Europe/Lisbon",
	"PW": "Pacific/Palau",
	"PY": "America/Asuncion",
	"QA": "Asia/Qatar",
	"RO": "Europe/Bucharest",
	"RS": "Europe/Belgrade",
	"RU": "Europe/Moscow", // capital Moscow
	"RW": "Africa/Kigali",
	"SA": "Asia/Riyadh",
	"SB": "Pacific/Guadalcanal",
	"SC": "Indian/Mahe",
	"SD": "Africa/Khartoum",
	"SE": "Europe/Stockholm",
	"SG": "Asia/Singapore",
	"SI": "Europe/Ljubljana",
	"SK": "Europe/Bratislava",
	"SL": "Africa/Freetown",
	"SM": "Europe/San_Marino",
	"SN": "Africa/Dakar",
	"SO": "Africa/Mogadishu",
	"SR": "America/Paramaribo",
	"ST": "Africa/Sao_Tome",
	"SV": "America/El_Salvador",
	"SY": "Asia/Damascus",
	"SZ": "Africa/Mbabane",
	"TD": "Africa/Ndjamena",
	"TG": "Africa/Lome",
	"TH": "Asia/Bangkok",
	"TJ": "Asia/Dushanbe",
	"TL": "Asia/Dili",
	"TM": "Asia/Ashgabat",
	"TN": "Africa/Tunis",
	"TO": "Pacific/Tongatapu",
	"TR": "Europe/Istanbul",
	"TT": "America/Port_of_Spain",
	"TV": "Pacific/Funafuti",
	"TZ": "Africa/Dar_es_Salaam",
	"UA": "Europe/Kyiv",
	"UG": "Africa/Kampala",
	"US": "America/Washington", // approximated as America/New_York
	"UY": "America/Montevideo",
	"UZ": "Asia/Tashkent",
	"VA": "Europe/Vatican",
	"VC": "America/St_Vincent",
	"VE": "America/Caracas",
	"VN": "Asia/Ho_Chi_Minh",
	"VU": "Pacific/Efate",
	"WS": "Pacific/Apia",
	"YE": "Asia/Aden",
	"ZA": "Africa/Johannesburg",
	"ZM": "Africa/Lusaka",
	"ZW": "Africa/Harare",
}

// GetTimezoneStringFromCountryCode returns the timezone for a given ISO 3166-1 alpha-2 country code.
func GetTimezoneStringFromCountryCode(countryCode string) string {
	return countryTimezone[countryCode]
}

// GetLocationFromCountryCode returns the timezone location for a given ISO 3166-1 alpha-2 country code.
func GetLocationFromCountryCode(countryCode string) (*time.Location, error) {
	tzStr := GetTimezoneStringFromCountryCode(countryCode)
	if tzStr == "" {
		return nil, fmt.Errorf("unknown country code: %s", countryCode)
	}

	loc, err := time.LoadLocation(tzStr)
	if err != nil {
		return nil, fmt.Errorf("failed to load location: %v", err)
	}
	return loc, nil
}
